---
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "dev"
    open-pull-requests-limit: 0  # security updates only
    ignore:
      - dependency-name: "ansible"
        versions:
          - ">=6.6.0"  # need Python 3.8 support
